apiVersion: v1
kind: Service
metadata:
  name: "${ZOOKEEPER_DEPLOYMENT_NAME}-service"
spec:
  selector:
    app: ${ZOOKEEPER_DEPLOYMENT_NAME}
  ports:
    - protocol: TCP
      port: ${ZOOKEEPER_PORT}
      targetPort: ${ZOOKEEPER_PORT}
